baseurl = "https://ndumas.com"
languageCode = "en-us"
theme = "terminal"
paginate = 5

googleAnalytics = "UA-113907906-1"
disqusShortname = "ndumas-com"

# pygmentsCodefences  = true
# pygmentsUseClasses  = true

rssLimit = 10  # Maximum number of items in the RSS feed.

[author]
  name = "Nick Dumas"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = true

  # center theme with default width
  centerTheme = false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[languages]
  [languages.en]
    languageName = "English"
    title = "code and stuff"
    subtitle = "sometimes i make stuff"
    keywords = ""
    copyright = "Nicholas Dumas 2020"
    menuMore = "lemme see"
    readMore = "read more"
    readOtherPosts = "explore"

    [languages.en.params.logo]
      logoText = "digital wizardry"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about-me"
      [[languages.en.menu.main]]
        identifier = "portfolio"
        name = "Portfolio"
        url = "/portfolio"
